id: A9A10EB21
title: f4DAE
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  - fr
  datatype: PlainText
  created_at: 2022-05-27 19:11:57.275725
  last_modified_at: 2022-05-27 19:11:57.275728
