id: A9A10EB21
title: f8391
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  - fr
  datatype: PlainText
  created_at: 2022-05-27 19:11:57.336805
  last_modified_at: 2022-05-27 19:11:57.336809
